### ISSUE TITLE
Léxico

### ISSUE THREAD

**Issue by lipeaaraujo** [UnBArqDsw2024-2/2024.2_G7_Entrega_Entrega_02#8]
# Descrição

Criar um artefato de léxicos seguindo o modelo proposto, organizando os termos essenciais do projeto para garantir consistência e clareza.

## Checklist

- [x] **Introdução**:
- [x] **Metodologia**:
- [ ] **Conteúdo**:
  - [x] Incluir léxicos relevantes do tipo Objeto.
  - [x] Incluir léxicos relevantes do tipo Verbo.
  - [x] Incluir léxicos relevantes do tipo Estado.
  - [ ] Adicionar outros tipos de léxicos, caso aplicável, como **Papéis** ou **Atributos**.
- [x] **Referências**:
- [ ] **Histórico de versões**

**Comment by kauaneiras** [comment]
# Descrição

Criar um artefato de léxicos seguindo o modelo proposto, organizando os termos essenciais do projeto para garantir consistência e clareza.

## Checklist

- [ ] **Introdução**:
- [ ] **Metodologia**:
- [ ] **Conteúdo**:
  - [ ] Incluir léxicos relevantes do tipo Objeto.
  - [ ] Incluir léxicos relevantes do tipo Verbo.
  - [ ] Incluir léxicos relevantes do tipo Estado.
  - [ ] Adicionar outros tipos de léxicos, caso aplicável, como **Papéis** ou **Atributos**.
- [ ] **Referências**:
- [ ] **Histórico de versões**
